services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 67:67/udp # Only required if you are using Pi-hole as your DHCP server
      - 82:80
      - 444:443
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      PIHOLE_DNS_: ${UNBOUND_NETWORK_IP}#5335 # Backup: 1.1.1.2;1.0.0.2;
      FTLCONF_LOCAL_IPV4: ${PIHOLE_FTLCONF_LOCAL_IPV4}
    networks:
    - dns
    volumes:
      - /home/${USER}/docker/files/pihole/etc-pihole:/etc/pihole
      - /home/${USER}/docker/files/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      - /home/${USER}/docker/files/pihole/etc-lighttpd/conf-enabled/:/etc/lighttpd/conf-enabled/
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    environment:
      TZ: ${TIMEZONE}
    # ports:
    #   - 5335:53/tcp
    #   - 5335:53/udp
    networks:
      dns:
        ipv4_address: ${UNBOUND_NETWORK_IP}
    volumes:
      - /home/${USER}/docker/files/unbound/config:/opt/unbound/etc/unbound/
      - /home/${USER}/docker/files/unbound/root.hints:/var/lib/unbound/root.hints
    restart: unless-stopped

  # Update duckdns with current external IP
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=true
    volumes:
      - /home/${USER}/docker/files/duckdns/config:/config
    restart: unless-stopped

networks:
  dns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${ROUTER_SUBNET}